### ISSUE TITLE
NikuWrap throws an error when inserting different subtype class into its children.

### ISSUE THREAD

**Issue by y-pakorn** [SaltyAom/niku#12]
When inserting `Widget` children through `NikuWrap` method, `TypeErrorImpl` will be thrown when the list subtype of `NikuWrap` constructor doesn't match with the subtype of the inserting child. Although `_children` property in `NikuWrap` constructor accepts any inherited `Widget` subtype.

Example
```dart
List<NikuColumn> someRandomColumnList = [1, 2, 3, 4].map((e) => NikuColumn(NikuText('$e'))).toList();
Container randomContainer = Container();

// This will throw an error. Expected a value of type 'NikuColumn', but got one of type 'Container'.
return NikuWrap(someRandomColumnList).insert(0, randomContainer);
// This also throw an error.
return NikuWrap(someRandomColumnList).append(randomContainer);

// But this will not.
return NIkuWrap(someRandomColumnList);
// This will not.
List<Widget> widgetList = someRandomColumnList.map((e) => e.build(context)).toList()
return NikuWrap(widgetList); // Build NikuColumn into generic `Widget` type first.
// This also not.
return NikuWrap(widgetList).append(randomContainer);
```

This might be an issue with dart forcing typecast into the parent subclass with assigning the `_children` property.

**Comment by y-pakorn** [comment]
This error might apply to `NikuColumn` and `NikuRow` as well. I haven't run the code to check yet.

**Comment by SaltyAom** [comment]
Hi, sorry for the late comment.

Every Niku Widget returns native Flutter Widget, you don't have to cast type to Niku Element.
You can check`NikuCore's internalBuild` which every Niku element rely on.

Here is a sample code that should work:
```dart
List<Widget> a() {
  final List<Widget> someRandomColumnList = [1, 2, 3, 4] //
      .map((e) => NikuColumn([NikuText('$e')]))
      .toList();

  someRandomColumnList.add(Container());
  someRandomColumnList.add(NikuButton(Text("Ok")));

  return someRandomColumnList;
}
```

<img width="1552" alt="Screen Shot 2564-09-08 at 10 19 11" src="https://user-images.githubusercontent.com/35027979/132441073-5488e853-62d9-4d5d-8933-4b4d7d9145be.png">

This way you can mix with other Widget 😁

**Comment by SaltyAom** [comment]
If this solves your problem, you can close the comment.

**Comment by SaltyAom** [comment]
Ok, so the build refers to `List<NikuColumn> on the inside which is weird.

Which mean this work:
<img width="1552" alt="Screen Shot 2564-09-08 at 10 21 58" src="https://user-images.githubusercontent.com/35027979/132441261-a26d87b2-9520-420e-9be7-d816e2412d39.png">

But this doesn't:
<img width="1552" alt="Screen Shot 2564-09-08 at 10 22 07" src="https://user-images.githubusercontent.com/35027979/132441273-4451e6b4-3b2d-414f-afea-307fffd60d34.png">

I'll fix that in the next release so you don't have to add `List<Widget>`.

**Comment by SaltyAom** [comment]
I tried fixing it by forcing typecast to the build method, seems not working.
I think this was Flutter type system problem, I'll see what I can do.

<img width="1552" alt="Screen Shot 2564-09-08 at 10 38 44" src="https://user-images.githubusercontent.com/35027979/132442648-18871d9f-411e-45cd-8926-ff7fe9f1ec27.png">

**Comment by y-pakorn** [comment]
I don't think we can alter Flutter's type cast system, for now. Maybe raising an issue in Flutter GitHub. 

So dynamic typing the variable is kinda workaround, you may close this issue if you want.

**Comment by SaltyAom** [comment]
Let's close this issue for now as we can't control or have any power in order to resolve the issue.
Feel free to open the issue again if Flutter has published a workaround to resolve this issue, thanks!
